created basic CRUD operations for rest of all models
f-lab-edu/realtor pull request #13
Opened 2023-03-30 10:44 UTC by sanghunjo921

issue: #12 

created CRUD operations for user, preferredProperties, agent, application and contract model
1. made serializers
2. made views
3. made urls

Refactoring: split models into a group that uses the same starting point for urls

todo: figure out how to make a urls.py when adding more than 1 id in a URL

2023-04-02 05:50 UTC, f-lab-stephen commented on realtor/transactions/urls.py
> +    # path("<int:pk>/contracts/<int:pk>", views.ContractDetail.as_view()),
이슈의 질문에 대한 답변도 여기서 하겠습니다. (사실 답변이 아니라 질문)

- <int:pk>로 넘어가는 URL parameter `pk`가 어디서 어떻게 사용되는지 알아보세요.
  - 참고로, 현재 `ContractList`에서 `pk` 값은 아예 사용되고 있지 않으며, 실제로는 Agent의 ID값이 아니라 Contract의 ID값을 가지고 있을 가능성이 높습니다.

2023-04-02 05:57 UTC, f-lab-stephen requested changes
대부분 CRUD 구현 측면에서 문제 없습니다! 다만 지금까지 되어 있는 부분에 대해 요청 스크린샷 PR에 코멘트로 올려 주시고, Foreign Key의 ID가 URL parameter로 필요한 경우에 대해서 해결하는 법을 조사해 주세요.

2023-04-03 05:02 UTC, sanghunjo921 commented
### **user**
<img width="516" alt="스크린샷 2023-04-03 오전 12 30 15" src="https://user-images.githubusercontent.com/119828758/229415768-e9b69271-d5c1-4415-a06a-4bf8a13b8ea8.png">
<img width="555" alt="스크린샷 2023-04-03 오전 12 30 28" src="https://user-images.githubusercontent.com/119828758/229415772-3478eb91-2999-402b-b568-4345b1a02b50.png">
<img width="585" alt="스크린샷 2023-04-03 오후 1 55 17" src="https://user-images.githubusercontent.com/119828758/229415774-2a17a434-475c-43e5-b825-9e8b985614aa.png">
<img width="549" alt="스크린샷 2023-04-03 오후 1 55 54" src="https://user-images.githubusercontent.com/119828758/229415776-6c65a98a-80c1-432e-ad48-861497f7aef5.png">

2023-04-03 05:03 UTC, sanghunjo921 commented
### **agent**
<img width="598" alt="스크린샷 2023-04-03 오후 1 57 21" src="https://user-images.githubusercontent.com/119828758/229415835-d2fc6b86-517b-451a-9659-52413304a995.png">
<img width="555" alt="스크린샷 2023-04-03 오후 1 59 16" src="https://user-images.githubusercontent.com/119828758/229415841-581f04f6-998a-43bf-b7b3-d8c5a98ceab4.png">
<img width="534" alt="스크린샷 2023-04-03 오후 1 57 38" src="https://user-images.githubusercontent.com/119828758/229415845-2383301c-af87-4421-8bf5-3d5be3848a95.png">
<img width="553" alt="스크린샷 2023-04-03 오후 1 57 27" src="https://user-images.githubusercontent.com/119828758/229415846-062c3f5d-a880-4024-87a6-184655cff9cc.png">
<img width="536" alt="스크린샷 2023-04-03 오후 1 56 15" src="https://user-images.githubusercontent.com/119828758/229415848-b9cc242e-86bd-4aaf-afd3-3e5f5df25a64.png">

2023-04-03 05:10 UTC, sanghunjo921 commented
### **application**
<img width="488" alt="스크린샷 2023-04-03 오후 2 04 33" src="https://user-images.githubusercontent.com/119828758/229416758-0e49512a-b87f-4393-95fa-73d6b3d022df.png">
<img width="488" alt="스크린샷 2023-04-03 오후 2 05 20" src="https://user-images.githubusercontent.com/119828758/229416767-852ce141-af86-4b73-bcbb-cd967814dbfb.png">

2023-04-03 05:10 UTC, sanghunjo921 commented
### **contract**
<img width="515" alt="스크린샷 2023-04-03 오후 2 09 16" src="https://user-images.githubusercontent.com/119828758/229416815-d7ad9d4b-8f0f-4e5a-9f96-205f499d11d2.png">
<img width="613" alt="스크린샷 2023-04-03 오후 2 09 38" src="https://user-images.githubusercontent.com/119828758/229416823-1d17750f-95bb-40f5-a968-e3703c3e8191.png">

2023-04-03 05:11 UTC, sanghunjo921 commented
preferredProperties
<img width="493" alt="스크린샷 2023-04-03 오후 2 08 45" src="https://user-images.githubusercontent.com/119828758/229416849-e4746567-111a-4830-a63a-612024cf7416.png">
<img width="537" alt="스크린샷 2023-04-03 오후 2 08 51" src="https://user-images.githubusercontent.com/119828758/229416856-989cb48b-96e4-4c03-abc9-d718530226d9.png">

2023-04-06 06:28 UTC, f-lab-stephen commented on realtor/realtor/serializers.py
이 부분 형상에서 없애 주세요. `git stash` 이용해서 잠깐 형상에서 뺐다가 `git stash pop` 명령어로 로컬로 되돌릴 수 있습니다. 이 방법으로 삭제하지 않고도 형상에 남기지 않을 수 있습니다.

2023-04-06 06:28 UTC, f-lab-stephen commented on realtor/realtor/views.py
위에 언급한 코멘트와 동일

2023-04-06 06:31 UTC, f-lab-stephen commented on realtor/transactions/serializers.py
> +        fields = ["id", "username", "password", "email", "phone", "rating", "date_joined"]
Serializer 필드에 password는 빼야 합니다.

2023-04-06 06:32 UTC, f-lab-stephen commented on realtor/transactions/urls.py
> +    path("<int:a_pk>/contracts/<int:pk>", views.ContractDetail.as_view()),
여기는 아직 진행중인 건가요?

2023-04-06 06:35 UTC, f-lab-stephen commented on realtor/users/serializers.py
> +            "password",
password 제외

2023-04-06 06:35 UTC, sanghunjo921 commented on realtor/transactions/urls.py
> +    path("<int:a_pk>/contracts/<int:pk>", views.ContractDetail.as_view()),
모델 관계 정리하다보니 너무 수정된 줄이 길어져서 저부분 들어가기 전에 모델 관계부분 컨펌받고자 일단 푸쉬했습니다. pk 부분은 리서치는 했는데 이슈 보니깐 더 중요도가 높은 작업이 있어서 모델 관계부분 컨펌받고 중요도 높은 token부터 처리하려고 했습니다.

2023-04-06 06:35 UTC, sanghunjo921 commented on realtor/users/serializers.py
> +            "password",
옙

2023-04-06 06:38 UTC, f-lab-stephen commented on realtor/transactions/urls.py
> +    path("<int:a_pk>/contracts/<int:pk>", views.ContractDetail.as_view()),
좋습니다! 완성된 것이 아니라도 계속 푸쉬하고 리뷰 받는 게 좋습니다. 작업중이시니 일단 PR을 draft로 바꾸겠습니다.

별도의 이슈는 별도의 PR로, 별도의 PR은 별도의 브랜치에서 작업하셔야 합니다! 새 브랜치는 현재의 메인에서 따 주세요.

2023-04-06 06:44 UTC, sanghunjo921 commented on realtor/transactions/urls.py
> +    path("<int:a_pk>/contracts/<int:pk>", views.ContractDetail.as_view()),
넵 ! 일단 형상 제외하고 serializers에 패스워드 삭제 빠르게 하고 푸쉬했습니다. 

이제 중요도 높은쪽부터 처리하도록 하겠습니다.

2023-04-25 04:24 UTC, closed without merging