created signup functionality
f-lab-edu/realtor pull request #16
Opened 2023-04-07 15:51 UTC by sanghunjo921

issue: #15 
followed blog guideline to add signup 

Under an authentication folder 
- created views.py
- created urls.py
- created serializers.py

2023-04-07 15:52 UTC, sanghunjo921 commented
일단 에러들 처리 후 signup에 대한 부분이 code가 너무 길어져서 pr 올립니다!

추후 로그인 등 기능 마저 넣겠습니다.

2023-04-09 06:29 UTC, f-lab-stephen commented on realtor/authentication/views.py
> +                    Token.objects.create(user=user)
블로그는 큰 틀에서 참고할 수 있지만 코드를 가져올 땐 잘 따져보고 가져오면 좋습니다!

이 뷰는 한 유저의 회원가입을 위한 뷰인데, 그 때마다 기존 유저 전체를 순회한다는 것은 말이 안 되는 것 같네요.
유저 전체 쿼리 1회 + 유저마다 토큰 생성 혹은 획득 N회 해서 총 N+1회의 쿼리가 발생하는 것이죠.

블로그 글에서 일단 회원가입 부분 예시가 잘 들어가 있어서 링크해 드리긴 했는데, 코드 전체는 부분부분 개판인 데가 많군요,, ㅠㅠ

2023-04-10 08:06 UTC, sanghunjo921 commented on realtor/authentication/views.py
> +                    Token.objects.create(user=user)
흠... 관련된 내용 리서치중인데 jwt나 all-auth 이용하면 알아서 다해주니 편하긴 한데 이러면 직접 구현하는 의미가 없네요 ㅋㅋ....

2023-04-10 08:29 UTC, sanghunjo921 commented
<img width="553" alt="스크린샷 2023-04-10 오후 5 28 26" src="https://user-images.githubusercontent.com/119828758/230863975-92808b4d-0766-4327-9236-ae0e8f5f8bf8.png">

2023-04-10 13:52 UTC, f-lab-stephen commented on realtor/authentication/views.py
> +        except IntegrityError as e:
`IntegrityError`는 어떤 경우에 발생하나요?
- 서버쪽 문제로 발생한다면
  - `IntegrityError`가 처음부터 안 나게 코드를 수정
  - 불가능하거나 쉽지 않다면 그냥 `IntegrityError`로 500이 나도록 하는 게 차라리 낫습니다. (4xx: your fault, 5xx: my fault)
- 유저의 잘못된 입력으로 인한 것이라면 `ValidationError`로 처리하는 것이 맞습니다.

2023-04-10 13:55 UTC, f-lab-stephen requested changes

2023-04-10 13:55 UTC, f-lab-stephen commented on realtor/authentication/views.py
> +        # )
PR 완성본에서는 앞으로 사용되지 않을 주석은 지워주세요.

2023-04-10 13:55 UTC, f-lab-stephen commented on realtor/realtor/urls.py
> +    # path('rest-auth/registration/', include('rest_auth.registration.urls')),
마찬가지

2023-04-10 13:57 UTC, f-lab-stephen commented on realtor/authentication/views.py
> +        except IntegrityError as e:
코드 상으로 봤을 때 User의 생성 부분에서 unique한 값의 중복체크 없이 생성하게 되어 있어서 그럴 가능성이 있겠네요. DB에 INSERT 쿼리를 날리는 것으로 중복 체크를 하는 것은 너무 비싸죠?

2023-04-10 14:13 UTC, f-lab-stephen commented on realtor/authentication/views.py
> +class RegistrationView(APIView):
Sign-in 뷰에 대해서는 추가 PR로 작업하실 예정인가요?

현재 구조에서는 회원가입때 받은 토큰을 잃어버리거나 하면 다시 받을 방법이 없겠네요. Sign-in은 `username`, `password`를 확인해서 통과하면 `Token.objects.get()` 정도로 간단하게 구현할 수 있습니다.

2023-04-10 14:17 UTC, f-lab-stephen commented on realtor/authentication/views.py
> +                data = registration_serializer.errors
제 생각에 이상적으로는 아예 회원가입 시에 토큰을 안 주고, data는 `registration_serializer.data`를 넘기는 것으로 충분하지 않을까 싶네요.

현재 형태로 하고자 하시면 적어도 JSON 형태로 어떤 값이 어떤 뜻인지 정도라도 표시해 줄 수 있으면 좋겠습니다.

```py
data = {
    "message": "user registered successfully",
    "email": user.email,
    "username": user.username,
    "token": token,
}

2023-04-10 14:18 UTC, f-lab-stephen commented on realtor/authentication/views.py
> +                data = registration_serializer.errors
23~27라인에 대한 코멘트입니다! 잘못 마킹했네요

2023-04-11 06:59 UTC, f-lab-stephen commented
> serializers.py resgistrationSerializer에 <img alt="스크린샷 2023-04-11 오후 3 29 20" width="720" src="https://user-images.githubusercontent.com/119828758/231074867-4a53633b-a592-4791-868e-6272c5d1a40b.png">
> 
> 이런식으로 추가해서 views.py에서 통과하면 토큰을 주는식인가요?

네 그 때 토큰을 넘겨 주는 방식이면 좋겠습니다. 그리고 캡쳐된 코드에서 username과 email을 같다고 간주하고 사용하신 것 같은데, 그렇지 않을 것 같네요. 실제로 `IntegrityError`를 유발하는 필드는 `username`인 것으로 보입니다. ([장고 소스 코드 참조](https://github.com/django/django/blob/main/django/contrib/auth/models.py#L334-L358))

그럼에도 우리 서비스는 username과 email이 같다! 라는 원칙을 세우셨다면 그렇게 하셔도 문제 없습니다. 다만 두 필드는 장고에서 엄연히 다르게 존재한다는 것만 기억해 주세요.

그러므로 실제로 필요한 것은 `validate_username`입니다. `validate_email`도 물론 있어서 나쁘지 않습니다. 두 validator의 경우에 가능하면 `if User.objects.filter(username=username).exists():`로 바꿔 주세요. 성능 개선 차이는 크지 않을 것으로 보이지만 의미가 좀 더 명확해지는 장점이 있습니다. 적어도 더 느리지는 않습니다.

2023-04-11 07:08 UTC, sanghunjo921 commented
> 우리 서비스는 username과 email이 같다! 라는 원칙을 세우셨다면 그렇게 하셔도 문제 없습니다. 다만 두 필드는 장고에서 엄연히 다르게 존재한다는 것만 기억해 주세요.

저가 serializer에서 필드에 username을 지웠어요. 이유는 다른 사이트에서 회원가입할때 생각해보면 email이 username이 된적이 많아서 저런식으로 처리해서 로그인 자체를 이메일로 해도 되는지 궁금해서 한번 해봤습니다.

2023-04-11 08:53 UTC, sanghunjo921 commented
음... serializer에서 create할때 
        username = validated_data["username"]
        first_name = validated_data["first_name"]
        last_name = validated_data["last_name"]
        email = validated_data["email"]
        password = validated_data["password"]
이런식으로 이루어지는데 validated_data 값에 username과 password가 true로 표시되네요. views.py에서 serializer만들때 보내주는 request.data에는 제대로 들어가있구요. username과 password 값 자체가 true로 설정되있어서 validate_username이 안되네요....

2023-04-11 09:06 UTC, sanghunjo921 commented
<img width="547" alt="스크린샷 2023-04-11 오후 6 04 53" src="https://user-images.githubusercontent.com/119828758/231111519-019e21af-b4e4-42f0-a819-d805dc00af4e.png">

여기서 username이 세글자보다 적으면 정상적으로 에러 메시지를 호출하는데 이미 있는 유저네임으로 만들시 저가 호출한 에러 메시지가 아닌 "A "user with that username already exists."가 호출되는거로 봐서는 abstractuser에 이미 해당 기능이 있는거 같아요

2023-04-12 13:37 UTC, f-lab-stephen commented
> <img alt="스크린샷 2023-04-11 오후 6 04 53" width="547" src="https://user-images.githubusercontent.com/119828758/231111519-019e21af-b4e4-42f0-a819-d805dc00af4e.png">
> 
> 여기서 username이 세글자보다 적으면 정상적으로 에러 메시지를 호출하는데 이미 있는 유저네임으로 만들시 저가 호출한 에러 메시지가 아닌 "A "user with that username already exists."가 호출되는거로 봐서는 abstractuser에 이미 해당 기능이 있는거 같아요

그러면 해당 메시지가 어디서 내려주는 것인지 장고 도큐먼트와 소스 코드를 확인하고 빼셔도 됩니다. 일단 장고에서 처리해 주는 것은 분명하니 나중에 확인만 해 주시고, 로직을 빼는 것은 편하신 대로 하시면 되겠습니다!

2023-04-12 13:38 UTC, f-lab-stephen commented
좋습니다! 이제 로그인 후 토큰이 발급되는 것 스크린샷만 올려 주시면 값만 이상 없으면 approve하도록 하겠습니다

2023-04-13 08:29 UTC, f-lab-stephen commented on realtor/authentication/serializers.py
> +        if user is None:
```suggestion
        if not user:
```

2023-04-13 08:32 UTC, f-lab-stephen approved these changes

2023-04-13 14:56 UTC, sanghunjo921 commented
<img width="587" alt="스크린샷 2023-04-13 오후 11 56 07" src="https://user-images.githubusercontent.com/119828758/231800097-989a0a34-9d78-4ee2-a256-369a529b5103.png">

login 부분 포스트맨 테스트 스크린샷입니다.

2023-04-14 04:24 UTC, f-lab-stephen approved these changes
고생 많으셨습니다! 매 PR 얻어가시는 게 있으면 좋겠네요! ㅎ_ㅎ

2023-04-14 04:31 UTC, merged