defined useradmin & propertyadmin
f-lab-edu/realtor pull request #17
Opened 2023-04-17 09:03 UTC by sanghunjo921

issue : #14 

- defined & registered userAdmin model
- defined & registered propertyAdmin model

2023-04-17 09:07 UTC, sanghunjo921 commented
일단 draft로 property & user 어드민 모델 부분 올렸습니다.

현재 브랜치에서 이전에 작업했던 code structure 부분이 적용되지 않아서 (url 구분에 따른 앱 나누는 부분이 아직 merge되지 않은 브랜치에 적용되어 있기에) 무시하고 현재 structure에 맞게 admin을 구현할지 아니면 한꺼번에 처리할지 고민입니다.

무시하고 admin을 구현시 모델의 위치가 바뀌면서 오히려 골치만 아파질꺼 같아서 이전 브랜치 참고하여 구조의 변경과 동시에 나머지 admin부분도 구현하는 방향으로 진행할 예정입니다.

2023-04-18 04:37 UTC, f-lab-stephen commented on realtor/realtor/settings.py
> +SITE_ID = 1
이 부분 추가에 대한 설명을 조금 더 추가해 줘도 좋겠습니다. (코멘트나 PR description을 통해)
맥락을 모르는 사람한테는 magic number처럼 보일 수도 있는 것이니까요.

2023-04-18 04:38 UTC, f-lab-stephen commented
여러가지 어드민 모델 옵션에 대해 충분히 실험해 보시고 가장 그럴듯 한 옵션이 되었다 싶으면 approve 요청해 주세요. 그리고 스크린샷에서 볼 때 `Property` 모델의 복수형이 좀 이상하게 표시되죠? 이 부분 옵션으로 수정할 수 있습니다.

2023-04-18 08:56 UTC, sanghunjo921 commented
feeback부분 반영했습니다.

그리고 code structure부분이랑 다른 모델들 views.py serializers.py 다시 정리했어요.
도중에 admin 페이지에서 property_user.id가 없는등 attribute에러등과 같은 에러들 처리했습니다.

현재 상태는 crud 정상적으로 동작하고 (pk 여러번 쓰는 url 제외) 만들어진 어드민 페이지 (property, user, agent, contract, application) 요청사항 동작합니다. 

앞으로 preferredProperty에 대한 어드민 페이지를 만들어야하고 options에서 숫자 필드를 범위로 지정하기 위해 numericRangeFilter를 쓰려고 하는데 존재하지 않는 에러가 나오네요. django rangefilter 소스코드상에 dateRangefilter와 numericRangeFilter 둘다 존재하는데 dateRangefilter는 정상적이지만 numericRangeFilter는 import가 안되는게 이상하네요. 

https://github.com/silentsokolov/django-admin-rangefilter/blob/master/rangefilter/filters.py

2023-04-18 15:28 UTC, sanghunjo921 commented
일단 기본적인 어드민 페이지는 모두 완성했다고 생각합니다.

installed_apps에서 suit은 찾다보니 어드민 페이지 스타일링을 제공해주는 패키지가 있어서 적용해봤습니다.

2023-04-19 04:45 UTC, f-lab-stephen requested changes
외부 디펜던시가 추가되었으면 Poetry 설정 파일도 수정이 되었을 것 같은데, (`poetry add [package_name]`으로 설치했다면) 이 부분과 lock file도 형상에 등록해 주셔야 할 것 같습니다. 예를 들어, 제가 현재 PR을 그대로 pull 받은 다음에 실행하면 dependency가 없다는 이유로 에러가 날 것입니다.

2023-04-19 04:46 UTC, f-lab-stephen commented
> 일단 기본적인 어드민 페이지는 모두 완성했다고 생각되네요.
> 
> installed_apps에서 suit은 찾다보니 어드민 페이지 스타일링을 제공해주는 패키지가 있어서 적용해봤습니다.

이런 추가적인 디테일은 당연히 좋지요! 기본적인 요구사항을 모두 달성한 뒤에 +a가 있다면 당연히 플러스 요소겠지요.

2023-04-19 06:14 UTC, sanghunjo921 commented
> 외부 디펜던시가 추가되었으면 Poetry 설정 파일도 수정이 되었을 것 같은데

poetry run pip install https://github.com/darklow/django-suit/tarball/v2 로 추가했어요

2023-04-20 05:00 UTC, f-lab-stephen commented
`poetry run pip install`보다 `poetry add`를 사용하셔야 하겠습니다. pyproject.toml 파일 업데이트와 동시에 venv에 pip install까지 해 주는 커맨드라서요. ([공식 문서 링크](https://python-poetry.org/docs/basic-usage/#specifying-dependencies))

이 프로젝트를 협업을 지금부터 시작하는 다른 개발자가 있다면, 본 repo를 pull한 후 `poetry install`을 한 후에 `poetry run python manage.py runserver`로 시작할 텐데, 이 과정이 제대로 이루어지려면 pyproject.toml 파일이 항상 동작하는 상태여야 합니다.

2023-04-20 10:50 UTC, sanghunjo921 commented
옙 말씀해주신데로 poetry add 통해서 형상에 올린후 push 했어요

2023-04-23 22:51 UTC, sanghunjo921 commented
깃헙에서 Error: Process completed with exit code 1 발생해서 알아보고 있는데 
아래 패키지 추가해서 생긴거 같네요..


[[package]]
name = "django-suit"
version = "2.0a2"
description = "Modern theme for Django admin interface."
category = "main"
optional = false
python-versions = "*"
files = [
    {file = "v2", hash = "sha256:b40c916de9528ca86bcccd42d1fd54e7773e5071d2bfd9efc576039c1a441c0b"},
]

[package.source]
type = "url"
url = "https://github.com/darklow/django-suit/tarball/v2"

2023-04-24 02:01 UTC, f-lab-stephen approved these changes
일단 지금 상태에서 동작하는 거죠? 고치고 싶은 부분이 있기는 한데 화요일에 같이 고쳐보기로 합시다! 일단 머지하시죠!

2023-04-24 02:20 UTC, merged