solved issue6
f-lab-edu/realtor pull request #8
Opened 2023-03-26 06:15 UTC by sanghunjo921

- made serializers 
- created generic views
- fixed urls.py

2023-03-26 07:03 UTC, f-lab-stephen commented
- [ ] PR 제목은 의미 있는 제목으로 해 주시고, #6 과 같이 시스템적으로 연결이 될 수 있게 링크를 해 주세요.

PR 변경 사항도 어떤 변경을 왜, 어떻게 했는지 설명해 주시면 더 좋겠습니다.

2023-03-26 07:21 UTC, f-lab-stephen requested changes
일단 아래 사항부터 먼저 리뷰드립니다! 전체에 대한 리뷰는 이 부분 해결되는 커밋 올라오기 전에 다시 드릴게요

2023-03-26 07:21 UTC, f-lab-stephen commented on realtor/.DS_Store
.gitignore 파일에 .DS_Store 파일을 제외하도록 제가 추가했는데, 뭔가 반영이 잘 안 되었나보네요? 해당 파일 형상에 반영되지 않도록 하는 법을 찾아서 반영해 보세요

2023-03-26 07:21 UTC, f-lab-stephen commented on realtor/properties/models.py
모델에 변경이 있으면 migration도 새로 만들어 주세요. (`poetry run python manage.py makemigrations`)

2023-03-26 07:21 UTC, f-lab-stephen commented on realtor/properties/models.py
또한, Choice를 이용할 때 default 값은 Choice 타입을 이용해서 만들어 주셔야 합니다. ([링크 참조](https://docs.djangoproject.com/en/4.0/ref/models/fields/#enumeration-types)) 숫자 1이 무엇을 뜻하는지 곧바로 알아보기 어렵습니다. (이것을 magic number라고 부르는데, magic number를 피하는 것은 아름다운 코드를 만드는 기본적인 방법입니다.)

2023-03-26 07:33 UTC, f-lab-stephen commented on realtor/realtor/urls.py
> +    path('', include('properties.urls')),
그러면 properties 이외에 users같은 것들도 `path(‘’, include(‘users.urls’))`와 같이 하게 되실 텐데, 그러면 에러가 나겠네요.

2023-03-26 08:02 UTC, sanghunjo921 commented on realtor/properties/models.py
옙 반영했습니다.

2023-03-26 08:13 UTC, sanghunjo921 commented on realtor/realtor/urls.py
> +    path('', include('properties.urls')),
처리했습니다.

2023-03-26 08:19 UTC, sanghunjo921 commented
gitignore 부분, url 에러 가능성 부분, choices 디폴트 값 처리, migrations, 커밋 시 자동으로 코드 수정부분 전부 반영해서 커밋 후 푸쉬를 눌렀는데 아마 현재 pr이 끝나지 않아서 그런지 Everything up-to-date 뜨네요!

2023-03-27 04:10 UTC, f-lab-stephen commented
@sanghunjo921 `git status`, `git log --oneline --decorate --graph`, `git branch` 결과물 보여주시겠어요?

2023-03-27 04:53 UTC, sanghunjo921 commented
<img width="592" alt="스크린샷 2023-03-27 오후 1 53 06" src="https://user-images.githubusercontent.com/119828758/227844114-aeccbab7-c8a7-44a6-b5e5-e7aed1a74339.png">
<img width="640" alt="스크린샷 2023-03-27 오후 1 53 25" src="https://user-images.githubusercontent.com/119828758/227844119-9256e964-651d-47ea-b26f-acaa4d2d0c0c.png">
<img width="404" alt="스크린샷 2023-03-27 오후 1 53 36" src="https://user-images.githubusercontent.com/119828758/227844123-bcc9229f-e99f-4686-841e-e236855fe1f2.png">

이런식으로 나오네요

2023-03-27 04:58 UTC, f-lab-stephen commented
커밋을 안 하셨네요! pre-commit이 발동되어서 reformatting을 하게 되면 커밋 자체가 되지 않고 다시 커밋해야 합니다.

2023-03-27 05:15 UTC, sanghunjo921 commented
> 커밋을 안 하셨네요! pre-commit이 발동되어서 reformatting을 하게 되면 커밋 자체가 되지 않고 다시 커밋해야 합니다.

흠.... 다시 커밋 해보긴 했는데 발동이 안되네요

2023-03-27 05:20 UTC, sanghunjo921 commented
branch를 새로 파서 커밋 날리고 푸쉬하니깐 잘 올라가네요

2023-03-27 10:57 UTC, f-lab-stephen commented
`git add .` 하고 새로 커밋 `git commit -m "Commit Message"` 해 주세요.

2023-03-27 14:21 UTC, merged